### PR TITLE
Fix/ledger c chain

### LINKED ISSUE #42: `setVaultManager` missing from the `middleware` commands

### LINKED ISSUE #43: ABI maybe should not be checked for `collateral-deposit` ?
ERC-20 ABI maybe should not be checked for `collateral-deposit` ? We never now if an ERC-20 is going to be 100% vanilla

I am facing this with the [ALOT](https://snowscan.xyz/address/0x51111e1f63D3341573882c0ed844e0876efd634d) contract

```bash
DEXALOT_COLLATERAL=0x51111e1f63D3341573882c0ed844e0876efd634d

suzaku-cli vault collateral-deposit \
          $DEXALOT_COLLATERAL \
          1 \
          -s suzaku-deployer
Approving collateral...
Detected EIP-1167 minimal proxy. Using implementation at address 0x8293d5421a90c1cbb6e358e639dd3421e79b1c0a for ABI validation.
ABI validation for contract ERC20 at address 0x093783055F9047C2BfF99c4e414501F8A147bC69: 12 selectors matched, 12 missing (50.00% missing)
Missing selectors: a217fddf, d5391393, 983b2d56, 84b0196e, 248a9ca3, 2f2ff15d, 91d14854, 40c10f19, 3092afd5, 36568abe, d547741f, 01ffc9a7
The contract at address 0x093783055F9047C2BfF99c4e414501F8A147bC69 does not match the expected ABI for ERC20 contract.
CLI Stack trace:
    at async approveAndDepositCollateral (/home/leo/Suzaku/suzaku-cli/dist/vault.js:119:25)
    at async /home/leo/Suzaku/suzaku-cli/dist/cli.js:391:9
    at async Command.wrappedFn (/home/leo/Suzaku/suzaku-cli/dist/lib/commandUtils.js:11:13)

```

EDIT: `--skip-abi-validation` can be used to skip validation

### LINKED ISSUE #46: `get-operator-l1-shares` should not `parseUnits` to `vault.read.decimals()`

### PR DESCRIPTION
**Pull request by servalD**
### Linked issues

- Fixes #43
- Fixes #42 
- Fixes #46 

### Changes

- Simplify CI/CD
- Fix empty bytes in selectors for ABI verification
- Add `account-info` middleware cmd (general info about if it's an operator (print these validators info) and detect its roles).

### CODE REVIEW

File: src/cli.ts [hunk 1]
```diff
@@ -1758,6 +1773,49 @@ async function main() {
             const validationIDs = await middlewareSvc.read.getOperatorValidationIDs([operator]);
             logger.log(`Validation IDs for operator ${operator}: ${validationIDs.join(', ')}`);
         });
+    
+    middlewareCmd
+        .command("account-info")
```
Comment (leopaul36) [inline src/cli.ts]: Useful but maybe we should find another name
